trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Nevotech Acr'
    repository: 'countdown-core-ui'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 1.0.$(Build.BuildNumber)